---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-proxy
  labels:
    k8s-app: kube-proxy
  namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
    interval: 30s
    scheme: http
    tlsConfig:
      insecureSkipVerify: true 
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-proxy
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-proxy
  labels:
    k8s-app: kube-proxy
spec:
  ports:
  - name: http-metrics
    port: 10249
  selector:
    k8s-app: kube-proxy
