- job_name: consul-node-exporter
  consul_sd_configs:
  - server: consul-ui.consul.svc:80
    services: []
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    regex: .*node-exporter.*
    action: keep
  - source_labels: [__meta_consul_service]
    target_label: job
- job_name: consul-nginx-exporter
  consul_sd_configs:
  - server: consul-ui.consul.svc:80
    services: []
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    regex: .*nginx-exporter.*
    action: keep
  - source_labels: [__meta_consul_service]
    target_label: job

- job_name: 'istiod'
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - istio-system
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: istiod;http-monitoring

- job_name: 'envoy-stats'
  metrics_path: /stats/prometheus
  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: keep
    regex: '.*-envoy-prom'
